const hre = require("hardhat");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying from:", deployer.address);

  // Deploy CommitmentRegistry
  const Registry = await hre.ethers.getContractFactory("CommitmentRegistry");
  const registry = await Registry.deploy();
  await registry.deployed();
  console.log("CommitmentRegistry:", registry.address);

  // Deploy Verifier (must exist — generated by snarkjs)
  const Verifier = await hre.ethers.getContractFactory("Verifier");
  const verifier = await Verifier.deploy();
  await verifier.deployed();
  console.log("Verifier:", verifier.address);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
